<?php
// i18n cn
return array(
'dict_projectname' => '档案馆世界地图',
'dict_theopenandcollaborative' => '开放与合作',
'dict_Languages' => '语言',
'dict_archivesname' => '名称',
'dict_archivesaddress' => '地址',
'dict_archivescity' => '城市',
'dict_archivesdistrict' => '区县',
'dict_archivescountry' => '国家',
'dict_archivesurl' => '链接',
'dict_archivesemail' => '邮箱',
'dict_archiveslatitude' => '纬度',
'dict_archiveslongitude' => '经度',
'dict_archivesyourname' => '您的名字（选填）',
'dict_archivesyouremail' => '您的邮箱（选填）',
'dict_archivesstatus' => '档案馆级别',
'dict_sendtoinclusion' => '发送给我们',
'dict_map' => '绘制地图',
'dict_collaborator' => '合作者',
'dict_collaboratoryou' => '合作伙伴',
'dict_collaboratoremail' => '合作者邮箱',
'dict_collaboratoremailobs' => '我们将不会把它显示给公众',
'dict_addarchives' => '添加一个机构',
'dict_about' => '关于',
'dict_home' => '主页',
'dict_contact' => '联系我们',
'dict_createdby' => '创建者',
'dict_textabout' => '<p>这是档案馆世界地图，一个以地图效果展示地球每一个档案机构的合作项目。也许这个目标听起来很远大，只要通过很多人的努力我们可以走得更远。</p><p>任何人都可以通过点击 <a href="http://map.arquivista.net/add">添加一个机构</a> 来向我们发送关于档案馆的信息。 当你向地图上添加机构时，<a href="http://ricardo.arquivista.net/english">项目维护人员</a>会对数据进行检查,然后将尽快地开放这些数据。数据库的使用是免费的，而且有望让其它项目也可使用这些数据。</p><p>档案馆世界地图网站和数据库达到一个足够稳定的状态以接收和存储可供多年使用的数据。</p><p>档案馆世界地图每个月维护费用约150英镑并且将由维护人员资助。如果您想为改进软件的计算资源和时间成本进行经济上的合作，您可以使用该页的最后一个按钮对项目进行每月的捐赠。</p><p>你也可以帮助将网页和软件翻译成您所在地方的语言。我们大约需要您提供翻译成50段话或文字的文件。用这种方式帮助仅需要发送邮件给 <img src="https://map.arquivista.net/etc/ricardoemail.png">.</p><p>要想收到关于这个项目的消息和改进的邮件，那就在 <a href="https://groups.google.com/d/forum/archives-world-map" target="_blank">https://groups.google.com/d/forum/archives-world-map</a> 上签名加入邮件组（只有维护人员可以发送电子邮件）。</p>',
'dict_howfindcoordinates' => ' <a href="https://itouchmap.com/latlong.html" target="_blank">如何定位到它</a>?',
'dict_textcontactpage' => '我们有一个联系方式。现在你可以发送消息给 <img src="https://map.arquivista.net/etc/ricardoemail.png">.',
'dict_thankscolab' => '感谢您的合作！文件将被审核并呈现在地图上。',
'dict_adddone' => '您所提交的信息已发送给认证者。如果一切顺利的话，信息将很快在档案馆世界地图上出现！谢谢！<br> - <i>Ricardo Sodré Andrade, 档案馆世界地图维护者</i>',
'dict_addfail' => '您所递交的信息没有发送成功。请输入正确的验证码。请再次尝试或联系项目维护人员。',
'dict_monthly' => '每月地',
'dict_textthankyoupage' => '感谢您每月的贡献！有了您的帮助我们将使档案馆世界地图项目继续下去！',
'dict_nameauthorisedform' => '如果可以的话，请使用 <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_EN.pdf" target="_blank">《档案馆藏机构著录规则》第16页</a> 解释的名称授权表。',
'dict_identifier' => '身份标识',
'dict_identifierform' => '如果可以的话，请输入 <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_EN.pdf" target="_blank">《档案馆藏机构著录规则》第16页</a> 说明的标识符。',
'dict_location' => '位置',
'dict_moreinformation' => '更多信息',
'dict_institution' => '机构',
'dict_search' => '搜索',
'dict_searchresults' => '搜索结果',
'dict_searchourdatabase' => '搜索我们的数据库',
'dict_awmwascreatedby' => '档案馆世界地图 (<a href="https://github.com/rsandrade/archives-worldmap" target="_blank">GitHub</a>)创始人是<br><a href="http://ricardo.arquivista.net/english" target="_blank">Ricardo Sodré Andrade</a>',
'dict_infoarchives' => '关于机构的信息', 
'dict_stats' => '统计数据',
'dict_statsof' => '数据统计',
'dict_institutionsdb' => '机构数据库',
'dict_top10countries' => '排名前10的国家',
'dict_decimaldegreesplease' => '如果可以的话，请采用<a href="https://en.wikipedia.org/wiki/Decimal_degrees" target="_blank">十进制形式</a>',
'dict_facebookcommunity' => '脸谱网',
'dict_facebookcommunity' => 'Facebook community',
);
