<?php
// Internacionalizacao EN_US
return array(
'dict_projectname' => 'Archives World Map',
'dict_theopenandcollaborative' => 'The open and collaborative',
'dict_Languages' => 'Change the language',
'dict_archivesname' => 'Institution (with archives open to public)',
'dict_archivesaddress' => 'Address',
'dict_archivescity' => 'City',
'dict_archivesdistrict' => 'District',
'dict_archivescountry' => 'Country',
'dict_archivesurl' => 'URL (website)',
'dict_archivesemail' => 'Email',
'dict_archiveslatitude' => 'Latitude',
'dict_archiveslongitude' => 'Longitude',
'dict_archivesyourname' => 'Your name (optional)',
'dict_archivesyouremail' => 'Your email (optional)',
'dict_archivesstatus' => 'Status',
'dict_sendtoinclusion' => 'Send to Archives World Map',
'dict_map' => 'map',
'dict_map_upper' => 'Map',
'dict_collaborator' => 'Collaborator name',
'dict_collaboratoryou' => 'Your name because we want to give credit',
'dict_collaboratoremail' => 'Collaborator email',
'dict_collaboratoremailobs' => 'We will not show it to the public',
'dict_addarchives' => 'Add an institution',
'dict_about' => 'About',
'dict_home' => 'Home',
'dict_contact' => 'Contact',
'dict_createdby' => 'Created by',
'dict_textabout' => '<p>This is the Archives World Map, a collaborative project to map every archival institutions in our planet. Maybe the objective sounds very ambitious but with the efforts of many people we can go far.</p><p>Anyone can collaborate using the link <a href="http://map.arquivista.net/add">add an institution</a> to send us some information about any archival institutions. The <a href="http://ricardo.arquivista.net/english">project maintaner</a> will check the data and will publish as fast as possible. The database is free to use and we want to provide a method soon to let other projects use our data.</p><p>The Archives World Map website and the database reached a stable enough state to receive and store the data to be used for many years ahead.</p><p>The Archives World Map costs around 150 € a month to exist and will be funded by the maintainer. If you want to collaborate financially for the computing resources and working hours costs for the software improvement, you can use the button at the end of this page to sign a monthly donation to the project.</p><p>You can help translating the website and software for your language also. Is just a file with around 50 phrases or words to be translated. To help in this way just send an email to <img src="https://map.arquivista.net/etc/ricardoemail.png">.</p><p>To receive emails about news and improvements of this project sign the email group (just the maintainer can send emails) at <a href="https://groups.google.com/d/forum/archives-world-map" target="_blank">https://groups.google.com/d/forum/archives-world-map</a>.</p>',
'dict_howfindcoordinates' => 'How to <a href="https://itouchmap.com/latlong.html" target="_blank">discover it</a>?',
'dict_textcontactpage' => 'We will have a contact form soon. Today you can send a message to <img src="https://map.arquivista.net/etc/ricardoemail.png">.',
'dict_thankscolab' => 'Thank you for your collaboration! The records will be verified soon to be published in the map.',
'dict_adddone' => 'Your submission was sent for verification. If everything be ok, the suggestion will appear soon in the Archives World Map! Thank you!<br> - <i>Ricardo Sodré Andrade, Archives World Map Maintainer</i>',
'dict_addfail' => 'Your submission was not sent. Maybe you did not checked the verification box (captcha) in add form. Please, try again or contact the project maintainer.',
'dict_monthly' => 'monthly',
'dict_textthankyoupage' => 'Thank you for your monthly contribution! With your help we will keep the Archives World Map alive!',
'dict_nameauthorisedform' => 'If possible, please use the Authorised Form of Name as explained by <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_EN.pdf" target="_blank">ISDIAH in page 16</a>.',
'dict_identifier' => 'Identifier',
'dict_identifierform' => 'If possible, please enter the Identifier as explained by <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_EN.pdf" target="_blank">ISDIAH in page 16</a>.',
'dict_location' => 'Location',
'dict_moreinformation' => 'More information',
'dict_institution' => 'Institution',
'dict_search' => 'Search',
'dict_searchresults' => 'Search result for',
'dict_searchourdatabase' => 'Search our database',
'dict_awmwascreatedby' => 'Archives World Map (<a href="https://github.com/rsandrade/archives-worldmap" target="_blank">GitHub</a>) was created by<br><a href="http://ricardo.arquivista.net/english" target="_blank">Ricardo Sodré Andrade</a>',
'dict_infoarchives' => 'Information about the Institution', 
'dict_stats' => 'Stats',
'dict_statsof' => 'Stats of Archives World Map',
'dict_institutionsdb' => 'Institutions',
'dict_top10countries' => 'Top 10 (countries)',
'dict_decimaldegreesplease' => 'If possible, in <a href="https://en.wikipedia.org/wiki/Decimal_degrees" target="_blank">Decimal Degrees</a>',
'dict_facebookcommunity' => 'Facebook community',
);
