<?php
// i18n ES
return array(
'dict_projectname' => 'Archives World Map',
'dict_theopenandcollaborative' => 'Colaborativo y abierto',
'dict_Languages' => 'Cambie el idioma',
'dict_archivesname' => 'Institución (archivo abierto al público)',
'dict_archivesaddress' => 'Dirección',
'dict_archivescity' => 'Ciudad',
'dict_archivesdistrict' => 'Estado/Distrito',
'dict_archivescountry' => 'País',
'dict_archivesurl' => 'URL (sitio web)',
'dict_archiveslatitude' => 'Latitud',
'dict_archiveslongitude' => 'Longitud',
'dict_archivesyourname' => 'Su nombre (opcional)',
'dict_archivesyouremail' => 'Su e.mail (opcional; no se publicará)',
'dict_collaboratoremailobs' => 'El e.mail no se publicará',
'dict_archivesstatus' => 'Status',
'dict_sendtoinclusion' => 'Enviar al Archives World Map',
'dict_map' => 'mapa',
'dict_map_upper' => 'Mapa',
'dict_collaborator' => 'Colaborador',
'dict_collaboratoryou' => 'Queremos acreditar la información',
'dict_collaboratoremail' => 'e.mail del colaborador',
'dict_addarchives' => 'Añadir una institución',
'dict_about' => 'Acerca de',
'dict_home' => 'Inicio',
'dict_contact' => 'Contacto',
'dict_createdby' => 'Creado por', 
'dict_textabout' => '<p>El Archives World Map es un proyecto colaborativo para mapear todas las instituciones archivísticas del planeta. Es un objetivo ambicioso pero que puede ser alcanzado con la colaboración de todos aquellos que estén dispuestos a ayudar en la construcción de esta base de datos. </p><p> La participación es gratuita, sólo es preciso entrar en el link <a href="http://map.arquivista.net/add">añadir una institución</a> y cumplimentar los datos. El <a href="http://ricardo.arquivista.net">administrador del proyecto</a> los verificará y, si están todos correctos, se publicarán en la base de datos. La base de datos es libre y en breve incorporará un sistema para que otros proyectos puedan reutilizar los datos.</p><p>El sitio web y la base de datos alcanzarán la madurez suficiente para conservar los datos correctamente para su uso en los próximos años.</p><p>El mantenimiento de este proyecto cuesta en torno a 150 € al mes y actualmente está financiado por el administrador, pero si desea colaborar económicamente para costear los recursos informáticos y las horas de trabajo dedicadas a la mejora del software, ver el final de esta página.</p><p>También puede ayudar a traducir el sitio web y el software a otro idioma. Actualmente se reduce a una lista de aproximadamente 50 frases o palabras. Si desea ayudar de esta forma, contacte con el administrador del proyecto en el correo.e <img src="https://map.arquivista.net/etc/ricardoemail.png">.</p><p>Para recibir mensajes sobre las novedades y avances de este proyecto, únase al grupo (sólo el administrador puede enviar mensajes) en <a href="https://groups.google.com/d/forum/archives-world-map" target="_blank">https://groups.google.com/d/forum/archives-world-map</a>.</p>',
'dict_howfindcoordinates' => 'Cómo <a href="https://itouchmap.com/latlong.html" target="_blank">encontrar las coordenadas</a>?',
'dict_textcontactpage' => 'Tendremos un formulario de contacto en breve. Por ahora, envíe un e.mail para <img src="https://map.arquivista.net/etc/ricardoemail.png">.',
'dict_thankscollab' => 'Gracias por su colaboración!',
'dict_adddone' => 'Su solicitud fue enviada para ser verificada. Si todo está correcto, sus datos aparecerán en el mapa en breve! Gracias!<br> - <i>Ricardo Sodré Andrade, administrador de Archives World Map</i>',
'dict_addfail' => 'Su solicitud no fue enviada. Probablemente no marcó la caja de verificación (CAPTCHA) del formulario de envió. Por favor, inténtelo de nuevo o contacte con el administrador del proyecto.',
'dict_monthly' => 'mensualmente',
'dict_textthankyoupage' => 'Gracias por su aportación mensual! Con su ayuda, vamos mantener y mejorar el Archives World Map!',
'dict_nameauthorisedform' => 'Si le es posible, por favor use la Forma Autorizada del Nombre como se explica en la <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_ES.pdf" target="_blank">ISDIAH en la página 16</a>.',
'dict_identifier' => 'Identificador',
'dict_identifierform' => 'Si le es posible, por favor introduzca el Identificador como se explica en la <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_ES.pdf" target="_blank">ISDIAH en la página 16</a>.',
'dict_location' => 'Localización',
'dict_moreinformation' => 'Más información',
'dict_institution' => 'Institución',
'dict_search' => 'Buscar',
'dict_searchresults' => 'Resultado de la búsqueda para ',
'dict_searchourdatabase' => 'Buscar en nuestra base de datos',
'dict_awmwascreatedby' => 'Archives World Map (<a href="https://github.com/rsandrade/archives-worldmap" target="_blank">GitHub</a>) está creado por<br><a href="http://ricardo.arquivista.net/perfil" target="_blank">Ricardo Sodré Andrade</a>',
'dict_infoarchives' => 'Información sobre la Institución',
'dict_stats' => 'Estadísticas',
'dict_statsof' => 'Estadísticas de Archives World Map',
'dict_institutionsdb' => 'Instituciones',
'dict_top10countries' => 'Top 10 (países)',
'dict_decimaldegreesplease' => 'Si le es posible en <a href="https://es.wikipedia.org/wiki/Grado_sexagesimal" target="_blank">grados sexagesimales</a>',
'dict_facebookcommunity' => 'Comunidad en Facebook',
);
