<?php
// i18n PL
return array(
'dict_projectname' => 'Mapa Świata Archiwów',
'dict_theopenandcollaborative' => 'Otwartość i współpraca',
'dict_Languages' => 'Zmień język',
'dict_archivesname' => 'Instytucja (z archiwum otwartym dla użytkowników)',
'dict_archivesaddress' => 'Adres',
'dict_archivescity' => 'Miasto',
'dict_archivesdistrict' => 'Województwo',
'dict_archivescountry' => 'Kraj',
'dict_archivesurl' => 'WWW',
'dict_archivesemail' => 'E-mail',
'dict_archiveslatitude' => 'Szerokość',
'dict_archiveslongitude' => 'Długość',
'dict_archivesyourname' => 'Twoje imię (opcjonalnie)',
'dict_archivesyouremail' => 'Twój e-mail (opcjonalnie)',
'dict_archivesstatus' => 'Status',
'dict_sendtoinclusion' => 'Wyśli do Mapa Świata Archiwów',
'dict_map' => 'Mapa',
'dict_map_upper' => 'Mapa',
'dict_collaborator' => 'Twórca',
'dict_collaboratoryou' => 'Twoje imię - dla uznania Twojego wkładu',
'dict_collaboratoremail' => 'Twój e-mail',
'dict_collaboratoremailobs' => 'Nie będzie widoczny w internecie',
'dict_addarchives' => 'Dodaj instytucję',
'dict_about' => 'O projekcie',
'dict_home' => 'Home',
'dict_contact' => 'Kontakt',
'dict_createdby' => 'Dodane przez',
'dict_textabout' => '<p> Mapa Świata Archiwów to projekt, którego celem jest zebranie informacji o wszystkich archiwach na świecie. Może to brzmi bardzo ambitnie, ale przy pomocy ochotników możemy zdziałać dużo.</p><p>Każdy może się przyłączyć <a href="http://map.arquivista.net/add">Dodaj instytucję</a> wysyłąjąc nam informacje o archiwach. <a href="http://ricardo.arquivista.net/english">Menadżer projektu</a> będzie zatwierdzał i publikował informacje tak szybko jak to możliwe. Korzystanie z bazy archiwów jest bezpłatne. W przyszłości z naszych danych będą mogły korzystać inne projekty.<p>Strona internetowa Mapy Świata Archiwów i baza danych są na tyle stabilne, aby gromadzić i przechowywać dane przez wiele lat.</p><p>Utrzymanie Mapy Świata Archiwów kosztuje około 150 € miesięcznie i jest finansowane przez menadżera projektu. Jeśli chcesz możesz wesprzeć projekt finansowo na rzecz pokrycia kosztów związanych z utrzymaniem infrastruktury i dalszym rozwojem oprogramowania. Klikając przycisk na dole strony możesz zarejestrować się jako darczyńca i wspierać projekt comiesięcznymi darowiznami.</p><p>Możesz również pomóc tłumacząc stronę i oprogramowanie na swój język – plik z 50 zdaniami lub słowami. Jeśli chcesz pomóc w ten sposób, to wystarczy, że wyślesz e-mail do <img src="https://map.arquivista.net/etc/ricardoemail.png">.</p><p>Żeby otrzymywać e-maile o nowościach i ulepszeniach projektu zapisz się do tej grupy (tylko menadżer proejtku może wysyłać e-maile) <a href="https://groups.google.com/d/forum/archives-world-map" target="_blank">https://groups.google.com/d/forum/archives-world-map</a>.</p>',
'dict_howfindcoordinates' => 'Jak ustalić dane geograficzne <a href="https://itouchmap.com/latlong.html" target="_blank"></a>? (instukcje po angielsku)',
'dict_textcontactpage' => 'Wktórtce będziemy mieli formularz kontaktowy. Na razie możesz  wysłać wiadomość do <img src="https://map.arquivista.net/etc/ricardoemail.png">.',
'dict_thankscolab' => 'Dziękujęmy za współpracę! Dane zostaną wktórtce zweryfikowane i opublikowane na mapie.',
'dict_adddone' => 'Twoje zgłoszenie zostało przesłane do weryfikacji. Jeśli wszystko będzie poprawne, to dane pojawią się wkrótce na Mapie Świata Archiwów! Dziękujemy!<br> - <i>Ricardo Sodré Andrade, Menadżer Projektu Mapa Świata Archiwów</i>',
'dict_addfail' => 'Twoje zgłoszenie nie zostało przesłane. Może pole weryfikacji (captcha) nie zostało zaznaczone? Prosimy spróbować ponownie lub skontaktować się z Menadżerem Projektu.',
'dict_monthly' => 'miesiecznie',
'dict_textthankyoupage' => 'Dziękujemy za comiesięczną darowiznę! Dzięki Twojej pomocy będziemy wstanie utrzymać Mapę Świata Archiwów! ',
'dict_nameauthorisedform' => 'Jeśli to możliwe, to użyj formy wzrocowej nazwy w rozumieniu standardu ISDIAH - Międzynarodowy Standard Opisu Instytucji z Zasobem Archiwalnym <a href="http://archiwa.org/as/as_img/uploaded/ISDIAHr.pdf" target="_blank">ISDIAH s. 12</a>.',
'dict_identifier' => 'Identyfikator',
'dict_identifierform' => 'Jeśli to możliwe, to użyj identyfikatora w rozumieniu standardu ISDIAH - Międzynarodowy Standard Opisu Instytucji
z Zasobem Archiwalnym <a href="httphttp://archiwa.org/as/as_img/uploaded/ISDIAHr.pdf" target="_blank">ISDIAH s. 12</a>.',
'dict_location' => 'Localizacja',
'dict_moreinformation' => 'Więcej informacji',
'dict_institution' => 'Instytucja',
'dict_search' => 'Szukaj',
'dict_searchresults' => 'Szukaj w rezultatach',
'dict_searchourdatabase' => 'Szukaj w bazie',
'dict_awmwascreatedby' => 'Mapa Świata Archiwów została stworzona przez <br><a href="http://ricardo.arquivista.net/english" target="_blank">Ricardo Sodré Andrade</a>',
'dict_infoarchives' => 'Informacje o instytucji', 
'dict_stats' => 'Statystyki',
'dict_statsof' => 'Statystyki Mapy Świata Archiwów',
'dict_institutionsdb' => 'Instytucje',
'dict_top10countries' => 'Top 10 (kraje)',
'dict_decimaldegreesplease' => 'Jeśli to możliwe <a href="https://en.wikipedia.org/wiki/Decimal_degrees" target="_blank">to w systemie dziesiętnym</a>',
);
