<?php
// Internacionalizacao PT_BR
return array(
'dict_projectname' => 'Mapa Mundial de Instituições Arquivísticas',
'dict_theopenandcollaborative' => 'Colaborativo e aberto',
'dict_Languages' => 'Mude o idioma',
'dict_archivesname' => 'Instituição (com arquivo aberto ao público)',
'dict_archivesaddress' => 'Endereço',
'dict_archivescity' => 'Cidade',
'dict_archivesdistrict' => 'Estado/Distrito',
'dict_archivescountry' => 'País',
'dict_archivesurl' => 'URL (website)',
'dict_archivesemail' => 'Email',
'dict_archiveslatitude' => 'Latitude',
'dict_archiveslongitude' => 'Longitude',
'dict_archivesyourname' => 'Seu nome (opcional)',
'dict_archivesyouremail' => 'Seu email (opcional; não publicaremos)',
'dict_collaboratoremailobs' => 'O email não será publicado',
'dict_archivesstatus' => 'Status',
'dict_sendtoinclusion' => 'Enviar para Archives World Map',
'dict_map' => 'mapa',
'dict_map_upper' => 'Mapa',
'dict_collaborator' => 'Colaborador',
'dict_collaboratoryou' => 'Queremos dar o crédito pelas informações.',
'dict_collaboratoremail' => 'Email do colaborador',
'dict_addarchives' => 'Adicione uma instituição',
'dict_about' => 'Sobre',
'dict_home' => 'Inicial',
'dict_contact' => 'Contato',
'dict_createdby' => 'Criado por', 
'dict_textabout' => '<p>Esse é o Archives World Map, um projeto de mapeamento colaborativo de todas as instituições arquivísticas do planeta. Um objetivo que soa bastante ousado, mas que pode ser alcançado com a colaboração de todos que se dispuserem a ajudar na construção dessa base de dados.</p><p>A participação é gratuita, você só precisa entrar no link para <a href="http://map.arquivista.net/add">adicionar uma instituição</a> e inserir os dados. O <a href="http://ricardo.arquivista.net">mantenedor do projeto</a> vai verificar e, caso esteja tudo ok, será publicado na base de dados. A base de dados é aberta e será disponibilizada em breve um método para que outros projetos possam reutilizar nossos dados.</p><p>O website e a base de dados alcançaram estabilidade suficiente para considerarmos que os dados serão guardados devidamente para uso nos próximos anos.</p><p>Esse projeto custa em torno de 150 € por mês para funcionar e atualmente é financiado pelo mantenedor, mas se você quiser colaborar financeiramente para custeio dos recursos computacionais e das horas de trabalho para melhoria do software, verifique o final desta página.</p><p>Você também pode ajudar a traduzir o website e o nosso software para outro idioma. Atualmente isso se resume a uma lista de aproximadamente 50 frases ou palavras. Se desejar ajudar dessa forma, entre em contato com o mantenedor do projeto pelo email <img src="https://map.arquivista.net/etc/ricardoemail.png">.</p><p>Para receber mensagens sobre novidades e progressos deste projeto, assine o grupo (apenas o mantenedor pode enviar mensagens) em <a href="https://groups.google.com/d/forum/archives-world-map" target="_blank">https://groups.google.com/d/forum/archives-world-map</a>.</p>',
'dict_howfindcoordinates' => 'Como <a href="https://itouchmap.com/latlong.html" target="_blank">descobrir</a>?',
'dict_textcontactpage' => 'Teremos um formulário de contato em breve. Por enquanto, envie um email para <img src="https://map.arquivista.net/etc/ricardoemail.png">.',
'dict_thankscollab' => 'Obrigado pela sua colaboração!',
'dict_adddone' => 'Sua inclusão foi enviada para verificação. Se tudo der certo, sua sugestão aparecerá no mapa em breve! Obrigado!<br> - <i>Ricardo Sodré Andrade, mantenedor do Archives World Map</i>',
'dict_addfail' => 'Sua inclusão não foi enviada. Provavelmente você não marcou a caixa de verificação do formulário de submissão. Por favor, tente novamente ou contate o mantenedor do projeto.',
'dict_monthly' => 'mensalmente',
'dict_textthankyoupage' => 'Obrigado pela sua colaboração mensal! Com sua ajuda, vamos manter e melhorar o Mapa Mundial de Instituições Arquivísticas!',
'dict_nameauthorisedform' => 'Se possível, por favor use a Forma Autorizada do Nome como explicado pela <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_PT.pdf" target="_blank">ISDIAH na página 15</a>.',
'dict_identifier' => 'Identificador',
'dict_identifierform' => 'Se possível, por favor preencha com o Identificador como explicado pela <a href="http://www.ica.org/sites/default/files/CBPS_2008_Guidelines_ISDIAH_First-edition_PT.pdf" target="_blank">ISDIAH na página 15</a>.',
'dict_location' => 'Localização',
'dict_moreinformation' => 'Mais informação',
'dict_institution' => 'Instituição',
'dict_search' => 'Busca',
'dict_searchresults' => 'Resultado da busca para ',
'dict_searchourdatabase' => 'Busque em nossa base de dados',
'dict_awmwascreatedby' => 'Archives World Map (<a href="https://github.com/rsandrade/archives-worldmap" target="_blank">GitHub</a>) foi criado por<br><a href="http://ricardo.arquivista.net/perfil" target="_blank">Ricardo Sodré Andrade</a>',
'dict_infoarchives' => 'Informações sobre Instituição',
'dict_stats' => 'Estatísticas',
'dict_statsof' => 'Estatísticas do Archives World Map',
'dict_institutionsdb' => 'Instituições',
'dict_top10countries' => 'Top 10 (países)',
'dict_decimaldegreesplease' => 'Se possível, em <a href="https://pt.wikipedia.org/wiki/Coordenadas_geogr%C3%A1ficas#Graus_Decimais" target="_blank">Decimal Degrees</a>',
'dict_facebookcommunity' => 'Comunidade no Facebook',
);
